// Generated by scripts/generate-images.mjs — Wix AI hero image, imported to Wix Media.
export const HOMEPAGE_HERO_URL = "wix:image://v1/12f848_bedc1ce85d36498f86aaec037475029c~mv2.png/12f848_bedc1ce85d36498f86aaec037475029c.png#originWidth=1200&originHeight=896";
