// Generated by scripts/generate-images.mjs — Wix AI hero image, imported to Wix Media.
export const HOMEPAGE_HERO_URL = "https://static.wixstatic.com/media/12f848_bedc1ce85d36498f86aaec037475029c~mv2.png";
