// Generated by scripts/regenerate-diverse-images.mjs — Wix AI hero image, imported to Wix Media.
export const HOMEPAGE_HERO_URL = "wix:image://v1/12f848_d934a71ed7024523becb992692bcfc0d~mv2.png/12f848_d934a71ed7024523becb992692bcfc0d.png#originWidth=1200&originHeight=896";
